Repository quantified-uncertainty/roast-my-post, pull requests merged in 2025-08, with the labels that each got.

#121 Fix TypeScript/React 19 compatibility issues
  apps/web/package.json
  apps/web/src/lib/auth.ts
  apps/web/src/types/react-compat.d.ts
  apps/web/src/types/react-markdown.d.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#120 Implement unified URL structure for REST API and MCP server
  .gitignore
  README.md
  apps/mcp-server/FEATURES.md
  apps/mcp-server/src/index.ts
  apps/web/src/app/api/docs/[docId]/evals/[agentId]/rerun/route.ts
  apps/web/src/app/api/docs/[docId]/evals/[agentId]/route.ts
  apps/web/src/app/api/docs/[docId]/evaluations/route.ts
  apps/web/src/app/api/docs/[docId]/route.ts
  apps/web/src/app/api/experiments/[trackingId]/route.test.ts
  apps/web/src/app/api/jobs/[jobId]/__tests__/route.test.ts
  apps/web/src/app/docs/[docId]/components/EvaluationManagement.tsx
  apps/web/src/app/monitor/evals/page.tsx
  apps/web/src/components/AgentDetail/types.ts
  apps/web/src/components/ExportEvaluationButton.tsx
  apps/web/src/lib/analysis-plugins/plugins/math/math.test.ts
  apps/web/src/lib/document-operations.ts
  apps/web/src/lib/evaluation/exportXml.ts
Labels: Review effort 4/5

#124 Remove temporal comments and enforce code comments policy
  apps/web/src/app/api/agents/[agentId]/export-data/route.ts
  apps/web/src/app/api/documents/[slugOrId]/export/route.ts
  apps/web/src/app/docs/[docId]/evaluations/components/VersionDetails.tsx
  apps/web/src/app/monitor/evals/page.tsx
  apps/web/src/components/AgentDetail/tabs/EvaluationsTab.tsx
  apps/web/src/components/DocumentWithEvaluations/components/EvaluationView.tsx
  apps/web/src/components/EvaluationComments.tsx
  apps/web/src/lib/analysis-plugins/plugins/fact-check/commentGeneration.ts
  apps/web/src/lib/analysis-plugins/plugins/forecast/index.ts
  apps/web/src/lib/analysis-plugins/plugins/math/index.ts
  apps/web/src/lib/analysis-plugins/plugins/spelling/index.ts
  apps/web/src/lib/evaluation/exportXml.ts
  apps/web/src/lib/evaluation/types.ts
Labels: Review effort 2/5

#126 Fix: Shell script permissions and Claude settings sync for Git worktrees
  dev/scripts/fix-script-permissions.sh
  dev/scripts/setup-git-hooks.sh
  dev/scripts/sync-claude-permissions.sh
  dev/scripts/worktree-manager.sh
Labels: Review effort 3/5

#136 feat: Add Prisma $extends with fullContent computed field
  apps/web/src/components/DocumentWithEvaluations/index.tsx
  apps/web/src/lib/documentAnalysis/__tests__/comprehensiveAnalysis.highlights.test.ts
  apps/web/src/lib/documentAnalysis/__tests__/comprehensiveAnalysis.unit.test.ts
  apps/web/src/lib/documentAnalysis/__tests__/markdownPrepend.edge.test.ts
  apps/web/src/lib/documentAnalysis/__tests__/markdownPrepend.integration.test.ts
  apps/web/src/lib/documentAnalysis/comprehensiveAnalysis/__tests__/comprehensiveAnalysis.integration.test.ts
  apps/web/src/lib/documentAnalysis/comprehensiveAnalysis/prompts.ts
  apps/web/src/lib/documentAnalysis/highlightExtraction/__tests__/highlightExtraction.test.ts
  apps/web/src/lib/documentAnalysis/highlightExtraction/index.ts
  apps/web/src/lib/documentAnalysis/highlightExtraction/prompts.ts
  apps/web/src/lib/documentAnalysis/highlightGeneration/highlightValidator.ts
  apps/web/src/lib/documentAnalysis/linkAnalysis/__tests__/linkValidator.integration.test.ts
  apps/web/src/lib/documentAnalysis/linkAnalysis/index.ts
  apps/web/src/lib/documentAnalysis/linkAnalysis/linkAnalysisWorkflow.ts
  apps/web/src/lib/documentAnalysis/linkAnalysis/prompts.ts
  apps/web/src/lib/documentAnalysis/multiEpistemicEval/__tests__/multiEpistemicEval.integration.test.ts
  apps/web/src/lib/documentAnalysis/multiEpistemicEval/__tests__/multiEpistemicEval.unit.test.ts
  apps/web/src/lib/documentAnalysis/multiEpistemicEval/index.ts
  apps/web/src/lib/documentAnalysis/shared/pluginLocationWrappers.ts
  apps/web/src/lib/documentAnalysis/spellingGrammar/__tests__/spellingGrammar.integration.test.ts
  apps/web/src/lib/documentAnalysis/spellingGrammar/index.ts
  apps/web/src/models/Document.ts
  apps/web/src/models/Job.ts
  apps/web/src/utils/__tests__/documentContentHelpers.test.ts
  apps/web/src/utils/__tests__/documentPrependMismatch.test.ts
  apps/web/src/utils/documentContentHelpers.ts
  dev/docs/development/comprehensive-refactoring-plan.md
  internal-packages/ai/src/shared/types.ts
  internal-packages/ai/src/utils/documentContentHelpers.ts
  internal-packages/db/src/client.ts
Labels: Review effort 3/5

#138 Fix failing integration and LLM tests
  .github/workflows/manual-integration-tests.yml
  MANUAL-TESTING.md
  apps/web/src/__tests__/integration/ai-package.integration.test.ts
  apps/web/src/app/api/tools/perplexity-research/route.integration.test.ts
  apps/web/src/lib/documentAnalysis/__tests__/markdownPrepend.integration.test.ts
  apps/web/src/lib/documentAnalysis/__tests__/plugin-system-e2e.integration.test.ts
  apps/web/src/lib/documentAnalysis/linkAnalysis/linkAnalysisWorkflow.ts
  apps/web/src/lib/documentAnalysis/testUtils.ts
  internal-packages/ai/package.json
  internal-packages/ai/src/analysis-plugins/plugins/math/math.llm.test.ts
  internal-packages/ai/src/analysis-plugins/plugins/spelling/index.ts
  internal-packages/ai/src/analysis-plugins/plugins/spelling/spelling.llm.test.ts
  internal-packages/ai/src/tools/extract-math-expressions/extract-math-expressions.llm.test.ts
  package.json
  scripts/run-integration-tests.js
Labels: Review effort 4/5, Possible security concern

#141 Fix tool pages and Prisma browser compatibility issues
  apps/web/next.config.js
  apps/web/src/app/agents/[agentId]/versions/AgentVersionsClient.tsx
  apps/web/src/app/api/docs/[docId]/evals/[agentId]/route.ts
  apps/web/src/app/docs/[docId]/evals/[agentId]/page.tsx
  apps/web/src/app/tools/check-spelling-grammar/page-refactored.tsx
  apps/web/src/app/tools/check-spelling-grammar/page.tsx
  apps/web/src/app/tools/components/ToolError.tsx
  apps/web/src/app/tools/components/ToolPageTemplate.tsx
  apps/web/src/app/tools/detect-language-convention/page-refactored.tsx
  apps/web/src/app/tools/detect-language-convention/page.tsx
  apps/web/src/components/AgentDetail/tabs/EvaluationsTab.tsx
  apps/web/src/components/DocumentSearch.tsx
  apps/web/src/lib/__tests__/prisma-serializers.test.ts
  apps/web/src/lib/db-error-handler.ts
  apps/web/src/lib/prisma-serializers-client.ts
  apps/web/src/lib/prisma-serializers-improved.ts
  apps/web/src/lib/prisma-serializers.ts
  apps/web/src/lib/prisma.ts
  apps/web/src/models/Agent.ts
  apps/web/src/models/Job.ts
  apps/web/src/models/User.ts
  internal-packages/ai/src/types.ts
  internal-packages/db/browser.ts
  internal-packages/db/package.json
  internal-packages/db/src/index.ts
  internal-packages/db/src/types.ts
Labels: Review effort 4/5

#144 Fix MCP worktree configuration for automatic setup
  apps/mcp-server/configure-claude.js
  dev/scripts/configure-mcp-for-worktree.sh
Labels: Review effort 4/5

#145 Add debug comment system with visual improvements
  apps/web/src/app/docs/[docId]/reader/page.tsx
  apps/web/src/components/DocumentWithEvaluations/components/CommentsColumn.tsx
  apps/web/src/components/DocumentWithEvaluations/components/EvaluationCardsHeader.tsx
  apps/web/src/components/DocumentWithEvaluations/components/EvaluationView.tsx
  apps/web/src/components/DocumentWithEvaluations/index.tsx
  apps/web/src/components/DocumentWithEvaluations/types.ts
  apps/web/src/components/EvaluationComments.tsx
  internal-packages/ai/src/analysis-plugins/plugins/fact-check/index.ts
  internal-packages/ai/src/analysis-plugins/plugins/forecast/index.ts
  internal-packages/ai/src/analysis-plugins/plugins/math/commentGeneration.test.ts
  internal-packages/ai/src/analysis-plugins/plugins/math/commentGeneration.ts
  internal-packages/ai/src/analysis-plugins/plugins/math/index.ts
  internal-packages/ai/src/analysis-plugins/plugins/math/math.parallelization.test.ts
  internal-packages/ai/src/analysis-plugins/plugins/math/math.test.ts
  internal-packages/ai/src/analysis-plugins/plugins/spelling/index.ts
  internal-packages/ai/src/analysis-plugins/utils/CommentBuilder.ts
  internal-packages/ai/src/shared/types.ts
Labels: Review effort 4/5

#147 refactor: Migrate Agent architecture to DDD patterns
  apps/web/src/__tests__/tools/tools.e2e.test.ts
  apps/web/src/app/agents/[agentId]/edit/EditAgentClient.tsx
  apps/web/src/app/agents/[agentId]/edit/actions.ts
  apps/web/src/app/agents/[agentId]/page.tsx
  apps/web/src/app/agents/[agentId]/versions/page.tsx
  apps/web/src/app/agents/new/actions.ts
  apps/web/src/app/agents/new/page.tsx
  apps/web/src/app/api/agents/[agentId]/__tests__/route.test.ts
  apps/web/src/app/api/agents/[agentId]/documents/__tests__/route.test.ts
  apps/web/src/app/api/agents/[agentId]/documents/route.ts
  apps/web/src/app/api/agents/[agentId]/evaluations/__tests__/route.test.ts
  apps/web/src/app/api/agents/[agentId]/evaluations/route.ts
  apps/web/src/app/api/agents/[agentId]/review/__tests__/route.test.ts
  apps/web/src/app/api/agents/[agentId]/review/route.ts
  apps/web/src/app/api/agents/[agentId]/route.ts
  apps/web/src/app/api/agents/__tests__/route.test.ts
  apps/web/src/app/api/agents/route.ts
  apps/web/src/app/api/documents/search/__tests__/route.test.ts
  apps/web/src/app/api/documents/search/route.ts
  apps/web/src/app/docs/[docId]/reader/actions.ts
  apps/web/src/app/docs/new/actions.ts
  apps/web/src/application/services/AgentService.ts
  apps/web/src/application/services/ServiceFactory.ts
  apps/web/src/application/services/documentImport.ts
  apps/web/src/components/agent/agentFormFields.ts
  apps/web/src/infrastructure/database/repositories/AgentRepository.ts
  apps/web/src/infrastructure/external/articleImport.e2e.test.ts
  apps/web/src/models/Agent.ts
Labels: Review effort 4/5

#148 Optimize CI/CD Pipeline: 70% Speed Improvement with Parallelization
  .github/workflows/docker.yml
  .github/workflows/test.yml
  Dockerfile
  Dockerfile.worker
  apps/web/package.json
  claude/ideation/2025-08-07-01-evaluation-restructure-analysis.md
  turbo.json
Labels: Review effort 4/5, Possible security concern

#150 fix: improve Docker worker build with fail-fast validation
  .githooks/pre-push
  .github/workflows/docker-test.yml
  .npmrc
  CLAUDE.md
  DOCKER-QUICKSTART.md
  Dockerfile.worker
  apps/web/src/application/workflows/documentAnalysis/__tests__/comprehensiveAnalysis.highlights.test.ts
  apps/web/src/application/workflows/documentAnalysis/__tests__/comprehensiveAnalysis.unit.test.ts
  apps/web/src/application/workflows/documentAnalysis/__tests__/markdownPrepend.edge.test.ts
  apps/web/src/application/workflows/documentAnalysis/__tests__/selfCritique.test.ts
  dev/docs/infrastructure/docker-monorepo.md
  dev/scripts/debug-docker-worker.sh
  dev/scripts/docker-check-all.sh
  dev/scripts/docker-runtime-test.js
  dev/scripts/test-docker-builds.sh
  dev/scripts/test-docker-worker.sh
  dev/scripts/validate-monorepo.sh
  docker-compose.test.yml
  internal-packages/ai/.eslintrc.json
  internal-packages/ai/package.json
  internal-packages/ai/src/analysis-plugins/PluginLogger.ts
  internal-packages/ai/src/analysis-plugins/PluginManager.ts
  internal-packages/ai/src/analysis-plugins/TextChunk.ts
  internal-packages/ai/src/analysis-plugins/builders/FindingBuilder.ts
  internal-packages/ai/src/analysis-plugins/plugins/fact-check/commentGeneration.ts
  internal-packages/ai/src/analysis-plugins/plugins/fact-check/index.ts
  internal-packages/ai/src/analysis-plugins/plugins/forecast/commentGeneration.ts
  internal-packages/ai/src/index.ts
  internal-packages/ai/src/testing.ts
  internal-packages/ai/tsconfig.json
  internal-packages/ai/tsconfig.lint.json
  internal-packages/db/package.json
  package.json
  tsc
Labels: Review effort 2/5

#152 Fix: Remove unused Puppeteer dependency
  apps/web/package.json
  pnpm-lock.yaml
Labels: Review effort 1/5

#157 feat: complete tool migration with remaining 4 tools and enhanced architecture
  apps/web/src/app/tools/check-math-hybrid/page.tsx
  apps/web/src/app/tools/check-math-with-mathjs/page.tsx
  apps/web/src/app/tools/check-math/page.tsx
  apps/web/src/app/tools/components/GenericToolPage.tsx
  apps/web/src/app/tools/components/__tests__/GenericToolPage.test.tsx
  apps/web/src/app/tools/components/results/DocumentChunkerDisplay.tsx
  apps/web/src/app/tools/components/results/ForecastResultDisplay.tsx
  apps/web/src/app/tools/components/results/FuzzyTextLocatorDisplay.tsx
  apps/web/src/app/tools/components/results/MathCheckDisplay.tsx
  apps/web/src/app/tools/components/results/index.ts
  apps/web/src/app/tools/document-chunker/page.tsx
  apps/web/src/app/tools/forecaster-simple/page.tsx
  apps/web/src/app/tools/fuzzy-text-locator/page.tsx
  apps/web/src/app/tools/utils/__tests__/exampleTexts.test.ts
  apps/web/src/app/tools/utils/__tests__/resultFormatting.test.ts
Labels: Review effort 3/5

#162 Fix: Restore highlight saving and validation after PR #161 regression
  internal-packages/db/src/repositories/JobRepository.ts
  internal-packages/jobs/src/core/JobOrchestrator.ts
Labels: Review effort 2/5

#165 Fix: Restore markdownPrepend generation for all document creation paths
  apps/web/src/application/services/__tests__/documentMarkdownPrepend.integration.test.ts
  apps/web/src/models/Document.ts
  apps/web/src/shared/utils/__tests__/documentMetadata.test.ts
  internal-packages/ai/package.json
  internal-packages/ai/src/index.ts
  internal-packages/ai/src/workflows/documentAnalysis/linkAnalysis/index.ts
  internal-packages/ai/src/workflows/documentAnalysis/linkAnalysis/linkAnalysisWorkflow.ts
  internal-packages/ai/src/workflows/documentAnalysis/testUtils.ts
  internal-packages/ai/tsconfig.json
  internal-packages/db/src/repositories/DocumentRepository.ts
  internal-packages/domain/src/index.ts
  internal-packages/domain/src/services/DocumentService.ts
  internal-packages/domain/src/utils/documentMetadata.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#164 Fix math evaluation tool approximation handling and dashboard filtering
  CLAUDE.md
  dev/evaluations/README.md
  dev/evaluations/data/check-math-with-mathjs/test-cases.ts
  dev/evaluations/data/check-spelling-grammar/test-cases.ts
  dev/evaluations/jest.config.js
  dev/evaluations/package-lock.json
  dev/evaluations/package.json
  dev/evaluations/server/__tests__/index.test.ts
  dev/evaluations/server/__tests__/views.test.ts
  dev/evaluations/server/index.ts
  dev/evaluations/server/runner.ts
  dev/evaluations/server/runners/check-math-with-mathjs.ts
  dev/evaluations/server/runners/check-spelling-grammar.ts
  dev/evaluations/server/static/dashboard.js
  dev/evaluations/server/static/styles.css
  dev/evaluations/server/views.ts
  dev/evaluations/shared/BaseRunner.ts
  dev/evaluations/shared/TestInterfaces.ts
  dev/evaluations/shared/TestUtils.ts
  dev/evaluations/test-runner.ts
  dev/scripts/worktree-tmux.sh
  internal-packages/ai/src/tools/check-math-hybrid/index.ts
  internal-packages/ai/src/tools/check-math-hybrid/schemas.ts
  internal-packages/ai/src/tools/check-math-hybrid/types.ts
  internal-packages/ai/src/tools/check-math-with-mathjs/ARCHITECTURE.md
  internal-packages/ai/src/tools/check-math-with-mathjs/README.md
  internal-packages/ai/src/tools/check-math-with-mathjs/check-math-with-mathjs.e2e.test.ts
  internal-packages/ai/src/tools/check-math-with-mathjs/deterministic-comparison.integration.test.ts
  internal-packages/ai/src/tools/check-math-with-mathjs/index.ts
  internal-packages/ai/src/tools/check-math-with-mathjs/mathjs-parser-utils.test.ts
  internal-packages/ai/src/tools/check-math-with-mathjs/mathjs-parser-utils.ts
  internal-packages/ai/src/tools/check-math-with-mathjs/numeric-comparison.test.ts
  internal-packages/ai/src/tools/check-math-with-mathjs/numeric-comparison.ts
  internal-packages/ai/src/tools/check-math-with-mathjs/schemas.ts
  internal-packages/ai/src/tools/generated-readmes.ts
  internal-packages/ai/src/tools/generated-schemas.ts
  internal-packages/ai/src/tools/shared/math-schemas.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 4/5, Possible security concern

#172 Remove unused /docs/[docId]/evaluations page
  README.md
  apps/mcp-server/src/index.ts
  apps/web/src/app/docs/[docId]/actions/evaluation-actions.ts
  apps/web/src/app/docs/[docId]/components/EvaluationManagement.tsx
  apps/web/src/app/docs/[docId]/evaluations/EvaluationsClient.tsx
  apps/web/src/app/docs/[docId]/evaluations/components/AgentList.tsx
  apps/web/src/app/docs/[docId]/evaluations/components/JobDetails.tsx
  apps/web/src/app/docs/[docId]/evaluations/components/TaskLogs.tsx
  apps/web/src/app/docs/[docId]/evaluations/components/VersionDetails.tsx
  apps/web/src/app/docs/[docId]/evaluations/components/VersionHistory.tsx
  apps/web/src/app/docs/[docId]/evaluations/page.tsx
  apps/web/src/app/docs/[docId]/evaluations/types.ts
  apps/web/src/application/services/tools/createToolAPIHandler.test.ts
  apps/web/src/components/RerunButtonClient.tsx
Labels: Review effort 4/5

#173 Replace nanoid with built-in crypto for ID generation
  apps/web/package.json
  apps/web/src/app/api/batches/route.test.ts
  apps/web/src/app/api/batches/route.ts
  apps/web/src/application/services/__tests__/DocumentService.integration.test.ts
  apps/web/src/application/services/__tests__/documentMarkdownPrepend.integration.test.ts
  apps/web/src/application/workflows/ephemeral-batch-cascade.integration.test.ts
  apps/web/src/infrastructure/database/repositories/AgentRepository.ts
  apps/web/src/models/Document.ts
  apps/web/src/models/__tests__/Document.email-privacy.e2e.test.ts
  internal-packages/db/package.json
  internal-packages/db/src/index.ts
  internal-packages/db/src/repositories/DocumentRepository.ts
  internal-packages/db/src/repositories/JobRepository.ts
  internal-packages/db/src/utils/generateId.ts
  internal-packages/domain/package.json
  pnpm-lock.yaml
Labels: Review effort 4/5

#175 chore: Remove dead code and unused dependencies
  apps/web/package.json
  apps/web/src/__tests__/integration/ai-package.integration.test.ts
  apps/web/src/__tests__/maintenance/cleanup-expired-batches.test.ts
  apps/web/src/app/api/agents/[agentId]/batches/route.ts
  apps/web/src/app/api/agents/[agentId]/overview/route.ts
  apps/web/src/app/api/agents/[agentId]/review/route.ts
  apps/web/src/app/api/docs/[docId]/evals/[agentId]/route.ts
  apps/web/src/app/api/docs/[docId]/route.ts
  apps/web/src/app/api/documents/[slugOrId]/evaluations/route.ts
  apps/web/src/app/api/documents/search/route.ts
  apps/web/src/app/api/users/[userId]/agents/count/route.ts
  apps/web/src/app/api/users/[userId]/documents/count/route.ts
  apps/web/src/app/monitor/evals/page.tsx
  apps/web/src/app/tools/components/results/MathCheckDisplay.tsx
  apps/web/src/app/users/[userId]/agents/page.tsx
  apps/web/src/application/services/document-operations.ts
  apps/web/src/application/workflows/evaluation/evaluationQueries.ts
  apps/web/src/components/AgentDetail/tabs/DocumentsTab.tsx
  apps/web/src/components/AgentDetail/tabs/EvaluationsTab.tsx
  apps/web/src/components/AgentDetail/tabs/TestTab.tsx
  apps/web/src/components/DocumentWithEvaluations/config/markdown.tsx
  apps/web/src/components/DocumentWithEvaluations/types.ts
  apps/web/src/components/GradeBadge.tsx
  apps/web/src/components/SlateEditor.tsx
  apps/web/src/components/evaluation/EvaluationDetailsSection.tsx
  apps/web/src/components/experiments/AgentConfigForm.tsx
  apps/web/src/hooks/usePlainTextOffsets.ts
  apps/web/src/infrastructure/database/prisma-serializers-improved.ts
  apps/web/src/infrastructure/database/prisma-serializers.ts
  apps/web/src/infrastructure/external/articleImport.ts
  apps/web/src/infrastructure/http/api/middleware.ts
  apps/web/src/models/Document.ts
  apps/web/src/shared/types/languageConvention.ts
  apps/web/src/shared/types/next-auth.d.ts
  apps/web/src/shared/utils/typeUtils.ts
  apps/web/src/shared/utils/ui/commentPositioning.ts
  apps/web/tests/playwright/auth-helpers.ts
  apps/web/tests/playwright/tools-auth.spec.ts
  pnpm-lock.yaml
Labels: Review effort 1/5

#181 Complete Jest to Vitest migration for @roast/ai package
  apps/web/tests/playwright/tools-e2e-validation.spec.ts
  internal-packages/ai/src/analysis-plugins/__tests__/extraction-boundaries.integration.vtest.ts
  internal-packages/ai/src/analysis-plugins/__tests__/parallel-execution.integration.vtest.ts
  internal-packages/ai/src/analysis-plugins/plugins/forecast/forecast.integration.vtest.ts
  internal-packages/ai/src/analysis-plugins/utils/ChunkRouter.integration.vtest.ts
  internal-packages/ai/src/claude/wrapper.integration.vtest.ts
  internal-packages/ai/src/workflows/documentAnalysis/__tests__/markdownPrepend.integration.vtest.ts
  internal-packages/ai/src/workflows/documentAnalysis/__tests__/plugin-system-e2e.integration.vtest.ts
Labels: Review effort 2/5

#189 Feat/new user profile
  apps/web/src/app/settings/costs/error.tsx
  apps/web/src/app/settings/costs/loading.tsx
  apps/web/src/app/settings/error.tsx
  apps/web/src/app/settings/keys/error.tsx
  apps/web/src/app/settings/keys/loading.tsx
  apps/web/src/app/settings/loading.tsx
  apps/web/src/app/settings/profile/error.tsx
  apps/web/src/app/settings/profile/loading.tsx
  apps/web/src/app/users/[userId]/edit/EditUserClient.tsx
  apps/web/src/app/users/[userId]/edit/actions.ts
  apps/web/src/app/users/[userId]/edit/page.tsx
  apps/web/src/app/users/[userId]/error.tsx
  apps/web/src/app/users/[userId]/loading.tsx
  apps/web/src/app/users/[userId]/page.tsx
  apps/web/src/components/UserDetail.tsx
  apps/web/src/components/global-error.tsx
  apps/web/src/components/global-loading.tsx
  apps/web/src/components/users/cards/agents-card.tsx
  apps/web/src/components/users/cards/documents-card.tsx
  apps/web/src/components/users/cards/index.ts
Labels: Review effort 2/5

#207 Fix evaluation card display and improve status indicators
  apps/web/src/app/agents/page.tsx
  apps/web/src/app/docs/[docId]/components/EvaluationManagement.tsx
  apps/web/src/app/docs/[docId]/components/ManagementEvaluationCard.tsx
  apps/web/src/app/docs/[docId]/page.tsx
  apps/web/src/app/docs/new/page.tsx
  apps/web/src/application/services/AgentService.ts
  apps/web/src/components/DocumentWithEvaluations/REFACTORING_SUMMARY.md
  apps/web/src/components/DocumentWithEvaluations/components/EvaluationCard.tsx
  apps/web/src/components/DocumentWithEvaluations/components/EvaluationCardsHeader.tsx
  apps/web/src/components/DocumentWithEvaluations/components/EvaluationView.tsx
  apps/web/src/components/DocumentWithEvaluations/components/index.ts
  apps/web/src/components/DocumentWithEvaluations/index.tsx
  apps/web/src/components/DocumentWithEvaluations/types.ts
  apps/web/src/components/EvaluationCard/README.md
  apps/web/src/components/EvaluationCard/index.tsx
  apps/web/src/components/EvaluationCard/shared/CommentToggle.tsx
  apps/web/src/components/EvaluationCard/shared/EvaluationActions.tsx
  apps/web/src/components/EvaluationCard/shared/EvaluationHeader.tsx
  apps/web/src/components/EvaluationCard/shared/EvaluationStats.tsx
  apps/web/src/components/StatusBadge.tsx
  apps/web/src/infrastructure/database/repositories/AgentRepository.ts
  apps/web/src/models/Document.ts
  apps/web/src/shared/constants/statusColors.ts
  apps/web/src/shared/hooks/useEvaluationRerun.ts
  apps/web/src/shared/utils/agentSorting.ts
  apps/web/src/shared/utils/evaluationStatus.ts
  apps/web/src/shared/utils/text.ts
Labels: Review effort 3/5

#208 fix: show evaluation header for pending evaluations without versions
  apps/web/src/components/DocumentWithEvaluations/index.tsx
  apps/web/src/models/Document.ts
  apps/web/src/models/__tests__/Document.vtest.ts
Labels: Review effort 2/5

#216 Optimize document listing queries to fetch only needed data
  apps/web/src/app/docs/DocumentsResults.tsx
  apps/web/src/app/docs/page.tsx
  apps/web/src/app/users/[userId]/documents/page.tsx
  apps/web/src/models/Document.ts
  apps/web/src/models/DocumentListing.types.ts
Labels: Review effort 2/5

#210 feat: ssr document search
  apps/web/package.json
  apps/web/src/app/docs/DocumentsClient.tsx
  apps/web/src/app/docs/DocumentsResults.tsx
  apps/web/src/app/docs/SearchBar.tsx
  apps/web/src/app/docs/error.tsx
  apps/web/src/app/docs/loading.tsx
  apps/web/src/app/docs/page.tsx
  apps/web/src/app/users/[userId]/documents/page.tsx
  apps/web/src/components/ui/tabs.tsx
  apps/web/src/models/Document.ts
  apps/web/src/models/DocumentListing.types.ts
  internal-packages/db/package.json
  internal-packages/db/src/client.ts
  pnpm-lock.yaml
Labels: Review effort 3/5
