Repository quantified-uncertainty/roast-my-post, pull requests merged in 2025-09, with the labels that each got.

#229 Fix Playwright test failures due to Anthropic API credit errors
  apps/web/src/lib/api-error-utils.ts
  apps/web/tests/playwright/tools-e2e-validation.spec.ts
Labels: Review effort 2/5

#230 Improve document pages layout and card interactions
  apps/web/src/app/docs/DocumentsResults.tsx
  apps/web/src/app/docs/page.tsx
  apps/web/src/app/my-documents/page.tsx
  apps/web/src/components/DocumentsLayoutClient.tsx
Labels: Review effort 3/5

#232 Fix document duplication and preserve importUrl on refresh
  apps/web/src/app/api/monitor/jobs/route.ts
  apps/web/src/app/docs/page.tsx
  apps/web/src/app/monitor/jobs/page.tsx
  apps/web/src/app/my-documents/page.tsx
  apps/web/src/components/job/JobCard.tsx
  internal-packages/db/src/repositories/DocumentRepository.ts
  internal-packages/domain/src/services/DocumentService.ts
Labels: Review effort 2/5

#233 feat: Add job cancellation feature with admin tracking
  apps/web/src/app/api/monitor/jobs/[jobId]/cancel/route.ts
  apps/web/src/app/api/monitor/jobs/route.ts
  apps/web/src/app/docs/[docId]/evals/[agentId]/logs/page.tsx
  apps/web/src/app/docs/[docId]/evals/[agentId]/page.tsx
  apps/web/src/app/docs/[docId]/evals/[agentId]/versions/[versionNumber]/logs/page.tsx
  apps/web/src/app/docs/[docId]/evals/[agentId]/versions/[versionNumber]/page.tsx
  apps/web/src/app/docs/[docId]/page.tsx
  apps/web/src/app/monitor/jobs/page.tsx
  apps/web/src/application/services/job/status.tsx
  apps/web/src/components/DocumentEvaluationSidebar.tsx
  apps/web/src/components/EvaluationTabsWrapper.tsx
  apps/web/src/components/EvaluationVersionSidebar.tsx
  apps/web/src/components/JobStatusIndicator.tsx
  apps/web/src/components/job/JobSummary.tsx
  apps/web/src/shared/types/databaseTypes.ts
  internal-packages/db/prisma/migrations/20250901125856_add_job_cancellation/migration.sql
  internal-packages/db/prisma/schema.prisma
  internal-packages/db/src/types.ts
  internal-packages/jobs/src/core/JobOrchestrator.ts
  internal-packages/jobs/src/core/__tests__/JobOrchestrator.vtest.ts
Labels: Review effort 3/5

#234 Minor improvements and fixes
  apps/web/src/app/monitor/jobs/page.tsx
  apps/web/src/app/users/UsersClient.tsx
  apps/web/src/components/AgentDetail/Layout.tsx
  apps/web/src/components/AgentDetail/index.tsx
  apps/web/src/components/AuthHeader.tsx
  apps/web/src/components/DocumentWithEvaluations/components/DocumentMetadata.tsx
  apps/web/src/components/users/cards/agents-card.tsx
  apps/web/src/components/users/cards/documents-card.tsx
  claude/ideation/unlisted-documents-feature.md
  internal-packages/ai/src/analysis-plugins/PluginManager.ts
Labels: Review effort 2/5

#238 refactor: standardize plugin naming conventions
  internal-packages/ai/src/analysis-plugins/plugins/forecast/index.ts
  internal-packages/ai/src/analysis-plugins/plugins/math/index.ts
  internal-packages/ai/src/analysis-plugins/plugins/math/math.llm.vtest.ts
  internal-packages/ai/src/analysis-plugins/plugins/math/math.vtest.ts
  internal-packages/ai/src/analysis-plugins/plugins/spelling/index.ts
  internal-packages/ai/src/analysis-plugins/plugins/spelling/spelling.llm.vtest.ts
  internal-packages/ai/src/analysis-plugins/plugins/spelling/spelling.vtest.ts
  internal-packages/ai/src/tools/check-spelling-grammar/check-spelling-grammar.e2e.vtest.ts
Labels: Review effort 2/5

#240 Fix: Increase fact-checker capacity and add max_tokens error handling
  internal-packages/ai/src/analysis-plugins/plugins/fact-check/constants.ts
  internal-packages/ai/src/analysis-plugins/plugins/fact-check/index.ts
  internal-packages/ai/src/analysis-plugins/utils/ChunkRouter.ts
  internal-packages/ai/src/claude/wrapper.ts
  internal-packages/ai/src/tools/extract-factual-claims/index.ts
  internal-packages/ai/src/tools/fact-checker/index.ts
  internal-packages/ai/src/tools/generated-schemas.ts
Labels: Possible security concern, Review effort 2/5

#243 UI improvements for document management and privacy controls
  apps/web/package.json
  apps/web/src/app/docs/[docId]/components/EvaluationManagement.tsx
  apps/web/src/app/docs/[docId]/components/ManagementEvaluationCard.tsx
  apps/web/src/app/docs/[docId]/components/PrivacySection.tsx
  apps/web/src/app/docs/[docId]/edit/page.tsx
  apps/web/src/app/docs/[docId]/page.tsx
  apps/web/src/app/docs/[docId]/reader/actions.ts
  apps/web/src/app/docs/import/page.tsx
  apps/web/src/app/docs/new/CreateDocumentForm.tsx
  apps/web/src/components/DocumentActions.tsx
  apps/web/src/components/DocumentEvaluationSidebar.tsx
  apps/web/src/components/DocumentWithEvaluations/components/CommentToolbar.tsx
  apps/web/src/components/DocumentWithEvaluations/components/DocumentContent.tsx
  apps/web/src/components/DocumentWithEvaluations/components/DocumentMetadata.tsx
  apps/web/src/components/DocumentWithEvaluations/components/EvaluationView.tsx
  apps/web/src/components/EvaluationCard/shared/EvaluationActions.tsx
  apps/web/src/components/EvaluationCard/shared/EvaluationStats.tsx
  apps/web/src/components/ExportEvaluationButton.tsx
  apps/web/src/components/RerunButtonClient.tsx
  apps/web/src/components/evaluation/EvaluationDetailsSection.tsx
  apps/web/src/components/ui/radio-group.tsx
  apps/web/src/constants/ui-labels.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#247 perf: optimize comment modal navigation performance
  apps/web/src/components/DocumentWithEvaluations/components/CommentModalOptimized.tsx
  apps/web/src/components/DocumentWithEvaluations/components/EvaluationView.tsx
Labels: Review effort 2/5

#254 Fix submitterNotes type error
  internal-packages/domain/src/services/DocumentService.ts
Labels: Review effort 2/5

#256 Minor readme change, to test Vercel
  README.md
  apps/web/src/app/agents/page.tsx
  apps/web/src/app/docs/page.tsx
Labels: Review effort 1/5

#253 Feat/doc page
  apps/web/src/components/DocumentWithEvaluations/components/CommentActions.tsx
  apps/web/src/components/DocumentWithEvaluations/components/DocumentActions.tsx
  apps/web/src/components/DocumentWithEvaluations/components/DocumentContent.tsx
  apps/web/src/components/DocumentWithEvaluations/components/DocumentMetadata.tsx
  apps/web/src/components/DocumentWithEvaluations/components/EvaluationCard.tsx
  apps/web/src/components/DocumentWithEvaluations/components/EvaluationCardsHeader.tsx
  apps/web/src/components/DocumentWithEvaluations/components/EvaluationView.tsx
  apps/web/src/components/DocumentWithEvaluations/hooks/useScrollHeaderBehavior.ts
  apps/web/src/components/DocumentWithEvaluations/index.tsx
  apps/web/src/components/EvaluationCard/shared/EvaluationActions.tsx
  apps/web/src/components/HoverPopover.tsx
  apps/web/src/components/ui/button.tsx
  apps/web/src/shared/utils/text.ts
Labels: Review effort 3/5

#258 UI Cleanup: Consolidate evaluation page headers
  apps/web/src/app/docs/[docId]/components/EvaluationManagement.tsx
  apps/web/src/app/docs/[docId]/components/ManagementEvaluationCard.tsx
  apps/web/src/app/docs/[docId]/evals/[agentId]/logs/page.tsx
  apps/web/src/app/docs/[docId]/evals/[agentId]/page.tsx
  apps/web/src/app/docs/[docId]/evals/[agentId]/versions/[versionNumber]/logs/page.tsx
  apps/web/src/app/docs/[docId]/evals/[agentId]/versions/[versionNumber]/page.tsx
  apps/web/src/app/docs/[docId]/page.tsx
  apps/web/src/components/DocEvalPageHeader.tsx
  apps/web/src/components/DocumentEvaluationSidebar.tsx
  apps/web/src/components/DocumentWithEvaluations/components/CommentActions.tsx
  apps/web/src/components/DocumentWithEvaluations/components/DocumentActions.tsx
  apps/web/src/components/DocumentWithEvaluations/components/DocumentContent.tsx
  apps/web/src/components/DocumentWithEvaluations/components/DocumentMetadata.tsx
  apps/web/src/components/DocumentWithEvaluations/components/EvaluationAnalysisSection.tsx
  apps/web/src/components/DocumentWithEvaluations/components/EvaluationCard.tsx
  apps/web/src/components/DocumentWithEvaluations/components/EvaluationView.tsx
  apps/web/src/components/EvaluationCard/shared/CommentToggle.tsx
  apps/web/src/components/EvaluationCard/shared/EvaluationActions.tsx
  apps/web/src/components/EvaluationCard/shared/EvaluationHeader.tsx
  apps/web/src/components/EvaluationCard/shared/EvaluationStats.tsx
  apps/web/src/components/EvaluationComments.tsx
  apps/web/src/components/EvaluationTabsWrapper.tsx
  apps/web/src/components/evaluation/EvaluationContent.tsx
  apps/web/src/components/evaluation/EvaluationDetailsSection.tsx
  apps/web/src/constants/ui-labels.ts
Labels: Review effort 3/5

#261 ci: Enable CI for staging branch
  .github/workflows/integration-on-merge.yml
  .github/workflows/test.yml
Labels: Review effort 2/5

#263 fix: Make vercel.json a valid JSON object
  apps/web/vercel.json
Labels: Review effort 1/5

#276 Agent refactor sep 2025
  internal-packages/ai/README.md
  internal-packages/ai/src/analysis-plugins/PluginManager.ts
  internal-packages/ai/src/analysis-plugins/types/plugin-types.d.ts
  internal-packages/ai/src/analysis-plugins/types/plugin-types.d.ts.map
  internal-packages/ai/src/analysis-plugins/types/plugin-types.js
  internal-packages/ai/src/analysis-plugins/types/plugin-types.js.map
  internal-packages/ai/src/claude/__mocks__/wrapper.ts
  internal-packages/ai/src/claude/mockHelpers.ts
  internal-packages/ai/src/claude/testUtils.ts
  internal-packages/ai/src/claude/wrapper.integration.vtest.ts
  internal-packages/ai/src/claude/wrapper.vtest.ts
  internal-packages/ai/src/config.ts
  internal-packages/ai/src/types.ts
  internal-packages/ai/src/utils/costCalculator.ts
  internal-packages/ai/src/workflows/documentAnalysis/__tests__/plugin-system-e2e.integration.vtest.ts
  internal-packages/db/.eslintignore
  internal-packages/db/.eslintrc.json
  internal-packages/db/system-agents/agents/comprehensive-checker.ts
  internal-packages/db/system-agents/agents/fact-checker.ts
  internal-packages/db/system-agents/agents/forecast-checker.ts
  internal-packages/db/system-agents/agents/link-checker.ts
  internal-packages/db/system-agents/agents/math-checker.ts
  internal-packages/db/system-agents/agents/spelling-grammar.ts
  internal-packages/db/system-agents/types.ts
  internal-packages/db/tsconfig.json
  internal-packages/db/tsconfig.lint.json
Labels: Review effort 3/5
